// Traducciones para la interfaz
const translations = {
    es: {
        // Interfaz general
        analyzeBtn: "Analizar texto",
        clearBtn: "Borrar texto",
        newAnalysisBtn: "Nuevo análisis",
        loadingText: "Analizando texto con algoritmos avanzados...",
        loadingSubtext: "Este proceso tomará 10 segundos",
        resultsTitle: "Resultados del Análisis",
        conclusionTitle: "Conclusión",
        comparisonTitle: "Comparación con otras plataformas",
        metricsTitle: "Métricas detalladas",
        sentenceAnalysisTitle: "Análisis por oraciones",
        humanSentence: "Texto probablemente humano",
        aiSentence: "Texto posiblemente IA",
        aiHighSentence: "Alta probabilidad de IA",
        minCharsWarning: "El texto debe tener al menos 100 caracteres para ser analizado.",
        
        // Resultados
        aiProbability: "Este texto tiene un {0}% de probabilidad de haber sido generado por IA.",
        humanProbability: "Este texto tiene un {0}% de probabilidad de haber sido escrito por un humano.",
        highConfidence: "Alta",
        mediumConfidence: "Media",
        lowConfidence: "Baja",
        
        // Métricas
        perplexityMetric: "Perplejidad",
        perplexityDesc: "Mide cuán predecible es el texto. Valores bajos indican patrones más predecibles, típicos de la IA.",
        
        burstinessMetric: "Variabilidad",
        burstinessDesc: "Analiza los cambios en la estructura de las oraciones. Los humanos tienden a variar más la longitud y complejidad.",
        
        entropyMetric: "Entropía",
        entropyDesc: "Evalúa la aleatoriedad y complejidad del texto. Los textos humanos suelen tener mayor entropía.",
        
        coherenceMetric: "Coherencia",
        coherenceDesc: "Mide la consistencia temática y lógica. Valores muy altos pueden indicar una estructura demasiado perfecta.",
        
        varietyMetric: "Variedad Léxica",
        varietyDesc: "Evalúa la diversidad de vocabulario. Los humanos suelen usar vocabulario más diverso y menos repetitivo.",
        
        fluencyMetric: "Fluidez",
        fluencyDesc: "Analiza la calidad y naturalidad del lenguaje. Valores extremadamente altos pueden indicar un texto demasiado pulido.",
        
        relevanceMetric: "Pertinencia",
        relevanceDesc: "Evalúa la consistencia temática. La IA suele mantener mayor enfoque temático que los humanos.",
        
        repetitivePatternsMetric: "Patrones Repetitivos",
        repetitivePatternsDesc: "Analiza la repetición de estructuras y comienzos de oraciones. La IA tiende a usar patrones más repetitivos.",
        
        errorsAndNaturalnessMetric: "Naturalidad",
        errorsAndNaturalnessDesc: "Evalúa la presencia de elementos naturales como expresiones idiomáticas, autocorrecciones y referencias personales.",
        
        transitionAbruptnessMetric: "Transiciones Abruptas",
        transitionAbruptnessDesc: "Mide la naturalidad en las transiciones entre oraciones. La IA puede generar cambios temáticos sin conectores adecuados.",
        
        excessiveFormalityMetric: "Formalidad Excesiva",
        excessiveFormalityDesc: "Detecta el uso excesivo de lenguaje formal y estructuras pasivas, más comunes en textos generados por IA.",
        
        bleuMetric: "Similitud Estructural",
        bleuDesc: "Analiza patrones repetitivos entre oraciones. Valores altos indican estructuras similares, típicas de IA.",
        
        // Humanización
        humanizeTitle: "Texto Humanizado",
        humanizeBtn: "Humanizar texto",
        changesTitle: "Cambios realizados:",
        useTextBtn: "Usar este texto",
        
        // Studocu
        studocuTitle: "Comparación con documentos de Studocu",
        studocuDesc: "Compara este texto con documentos existentes en Studocu para verificar originalidad.",
        googleAuthBtn: "Iniciar sesión con Google"
    },
    en: {
        // General interface
        analyzeBtn: "Analyze text",
        clearBtn: "Clear text",
        newAnalysisBtn: "New analysis",
        loadingText: "Analyzing text with advanced algorithms...",
        loadingSubtext: "This process will take 10 seconds",
        resultsTitle: "Analysis Results",
        conclusionTitle: "Conclusion",
        comparisonTitle: "Comparison with other platforms",
        metricsTitle: "Detailed metrics",
        sentenceAnalysisTitle: "Sentence analysis",
        humanSentence: "Likely human text",
        aiSentence: "Possibly AI text",
        aiHighSentence: "High probability of AI",
        minCharsWarning: "Text must have at least 100 characters to be analyzed.",
        
        // Results
        aiProbability: "This text has a {0}% probability of being generated by AI.",
        humanProbability: "This text has a {0}% probability of being written by a human.",
        highConfidence: "High",
        mediumConfidence: "Medium",
        lowConfidence: "Low",
        
        // Metrics
        perplexityMetric: "Perplexity",
        perplexityDesc: "Measures how predictable the text is. Lower values indicate more predictable patterns, typical of AI.",
        
        burstinessMetric: "Burstiness",
        burstinessDesc: "Analyzes changes in sentence structure. Humans tend to vary more in length and complexity.",
        
        entropyMetric: "Entropy",
        entropyDesc: "Evaluates randomness and complexity of the text. Human texts usually have higher entropy.",
        
        coherenceMetric: "Coherence",
        coherenceDesc: "Measures thematic and logical consistency. Very high values may indicate a too perfect structure.",
        
        varietyMetric: "Lexical Variety",
        varietyDesc: "Evaluates vocabulary diversity. Humans tend to use more diverse and less repetitive vocabulary.",
        
        fluencyMetric: "Fluency",
        fluencyDesc: "Analyzes the quality and naturalness of language. Extremely high values may indicate an overly polished text.",
        
        relevanceMetric: "Relevance",
        relevanceDesc: "Evaluates thematic consistency. AI tends to maintain greater thematic focus than humans.",
        
        repetitivePatternsMetric: "Repetitive Patterns",
        repetitivePatternsDesc: "Analyzes repetition of structures and sentence beginnings. AI tends to use more repetitive patterns.",
        
        errorsAndNaturalnessMetric: "Naturalness",
        errorsAndNaturalnessDesc: "Evaluates the presence of natural elements such as idiomatic expressions, self-corrections, and personal references.",
        
        transitionAbruptnessMetric: "Abrupt Transitions",
        transitionAbruptnessDesc: "Measures naturalness in transitions between sentences. AI can generate thematic changes without proper connectors.",
        
        excessiveFormalityMetric: "Excessive Formality",
        excessiveFormalityDesc: "Detects excessive use of formal language and passive structures, more common in AI-generated texts.",
        
        bleuMetric: "Structural Similarity",
        bleuDesc: "Analyzes repetitive patterns between sentences. High values indicate similar structures, typical of AI.",
        
        // Humanization
        humanizeTitle: "Humanized Text",
        humanizeBtn: "Humanize text",
        changesTitle: "Changes made:",
        useTextBtn: "Use this text",
        
        // Studocu
        studocuTitle: "Comparison with Studocu documents",
        studocuDesc: "Compare this text with existing documents on Studocu to verify originality.",
        googleAuthBtn: "Sign in with Google"
    }
};
